[[contracts]]
fqn = "casper_trade_contracts::casper_trade_v2_pair::CasperTradeV2Pair"

[[contracts]]
fqn = "casper_trade_contracts::sample_tokens::SampleToken"

[[contracts]]
fqn = "casper_trade_contracts::factory::Factory"

[[contracts]]
fqn = "casper_trade_contracts::router::CasperTradeV2Router"