[[contracts]]
fqn = "casperswap_contracts::casperswap_v2_pair::CasperswapV2Pair"

[[contracts]]
fqn = "casperswap_contracts::sample_tokens::SampleToken"

[[contracts]]
fqn = "casperswap_contracts::factory::Factory"