[[contracts]]
fqn = "casper_trade_contracts::pair::Pair"

[[contracts]]
fqn = "casper_trade_contracts::pair::PairFactory"

[[contracts]]
fqn = "casper_trade_contracts::sample_tokens::SampleToken"

[[contracts]]
fqn = "casper_trade_contracts::factory::Factory"

[[contracts]]
fqn = "casper_trade_contracts::router::Router"