last_updated = "2025-11-14T12:57:06Z"

[[contracts]]
name = "Factory"
package_name = "Factory"
package_hash = "hash-6b11561b04679dc7d252cafbe51daacafe70ffa4b3fdfe7a272bb031f789c6d4"

[[contracts]]
name = "SampleToken"
package_name = "SampleTokenA"
package_hash = "hash-8fb186c67344ea7b849f7dc9ac0921da801af656cbdd474955f5519f2e35fe2f"

[[contracts]]
name = "SampleToken"
package_name = "SampleTokenB"
package_hash = "hash-2bd38ba9f8f71aea3d46d22fe7cc1ea13f591b66ccc0a38837e88bf0822bf520"

[[contracts]]
name = "WrappedNativeToken"
package_name = "WrappedNativeToken"
package_hash = "hash-ed151da791a8eb07d562fbac9fa68a29fd3a16d959ff760beb2b8ea1d2cc8763"

[[contracts]]
name = "Router"
package_name = "Router"
package_hash = "hash-c18f1c713babf48b12b8d1ac6ae88ae164a5e8d78ddfeabaac469fd12fe1dac5"

[[contracts]]
name = "Pair"
package_name = "TokenA_TokenB"
package_hash = "hash-b10a364fe47ee673207a4cf1176779235a42fb9bea7ef7a0494b6282005f5fae"

[[contracts]]
name = "Pair"
package_name = "TokenA_WCSPR"
package_hash = "hash-150e00f2e2cbb0278ebc5b1c7fe3e3d9dd42ccca4ded79a5d43f7ce265aa6098"

[[contracts]]
name = "Pair"
package_name = "TokenB_WCSPR"
package_hash = "hash-d925321b012dd53b652ffffaa89c84cef757cafd343c28733c18d042ab548c1e"
