last_updated = "2025-10-21T15:24:49Z"

[[contracts]]
name = "Factory"
package_name = "Factory"
package_hash = "hash-8ee2dacede0e7e4ac98a27b6b2e805e7e8bf883cd811f13f2aefcd255a49823a"

[[contracts]]
name = "SampleToken"
package_name = "SampleTokenA"
package_hash = "hash-af6f77a81da7bf9da26f1c204232b3deb0f8f1cf57bcdfe320386f33851a129d"

[[contracts]]
name = "SampleToken"
package_name = "SampleTokenB"
package_hash = "hash-03471901de2f0acad01200ed1f9e7ac81243c02869946d8157644e3d408d3d9b"

[[contracts]]
name = "WrappedNativeToken"
package_name = "WrappedNativeToken"
package_hash = "hash-a5d11235ae27d9b6c8e0151729ae5e20be9a07b9b044c3a9e5f4cd8570a337d6"

[[contracts]]
name = "CasperswapV2Router"
package_name = "CasperswapV2Router"
package_hash = "hash-b8472d033e0caf2201cfffaeaed429160d3aa4a30962dc3931b4ad0b1c13c8b9"

[[contracts]]
name = "CasperswapV2Pair"
package_name = "TokenA_TokenB"
package_hash = "hash-d610e14707821f5fbcb54e1355b372c7cc759f99a2ccd1ef74e2e42cecd21d61"

[[contracts]]
name = "CasperswapV2Pair"
package_name = "TokenA_WCSPR"
package_hash = "hash-68ac2eb49aa9fac6ea46ab7dae26c1e05a9b2d4a20c95ed7e982c777f1be65c3"

[[contracts]]
name = "CasperswapV2Pair"
package_name = "TokenB_WCSPR"
package_hash = "hash-0960f8321dd2a4458a26cbca2ec70db2584cab7217e8f06576bb9b1f558d1433"
